package com.codeskeptic.scanner.repository;

import com.codeskeptic.scanner.entity.Setting;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Spring Data JPA repository for the {@link Setting} aggregate, which maps the {@code settings}
 * table.
 *
 * <p>The identifier type is {@link String}: the {@code settings.key} column is a natural primary key,
 * assigned by the caller and never generated by the persistence provider. Consumers use the inherited
 * {@link JpaRepository} surface alone, so {@code GET /settings} renders the unpaged
 * {@code findAll(Sort)} collection, sorted on the {@code key} property — DL-039.
 *
 * <p>This interface declares no statement of its own, so the quoted {@code settings."key"} and
 * {@code settings."value"} column names of DL-061 are rendered by the persistence provider alone —
 * the {@code order by} clause of that sorted read included — and no native statement names them.
 *
 * <p>Transactions are demarcated by the calling service method, and a {@link Setting} is mapped to
 * its wire representation inside that same boundary. The {@code settings} table is created from the
 * annotations on {@link Setting} by {@code spring.jpa.hibernate.ddl-auto} — DL-026.
 */
// Ported from backend/app/db/database.py:L10-13 (faithful port) — see docs/DECISION_LOG.md
// The identifier type parameter is String, matching the assigned settings.key primary key — DL-069
// — see docs/DECISION_LOG.md
public interface SettingRepository extends JpaRepository<Setting, String> {
}
